### ISSUE TITLE
Filesystem tracking issue

### ISSUE THREAD

**Issue by bugadani** [card-io-ecg/norfs#1]
## MVP

 - card-io-ecg/card-io-fw#32 
 - card-io-ecg/card-io-fw#35

## Bugs

 - card-io-ecg/norfs#2

## Features

 - [x] GC algo to move blocks of a file (#4)
 - [x] #4
 - [x] #7
 - [x] #11 
 - [x] Keep space for GC (#4)
 - [x] #8
 - [ ] Return with an error if the GC needs to run but files/folders are open - FS state versioning?
 - [ ] #22 

Future opportunities and ideas I don't immediately need:

 - [ ] Allow appending to closed files - reallocates header
 - [ ] Seek while reading
 - [ ] Allow writing a file while reading another - lift "write = UB while reading" restriction
 - [x] Better estimate size of new metadata object (#4)
 - [ ] Rename/move file
 - [ ] Directories
       - #11
       - #16
 - [ ] Access multiple files at the same time
 - [ ] Batch multiple small, consecutive writes
 - [ ] Consider supporting odd-byte (3) write granularity
